version: 0.1.3.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\classicuo
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-dev'
environment:
  DEV_BUILD: true
build_script:
- cmd: >-
    nuget restore


    msbuild "c:\projects\classicuo\ClassicUO.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=x64 /p:DefineConstants="DEV_BUILD" /p:OutputType=WinExe


    xcopy "c:\projects\classicuo\tools\monokickstart\*.*" "c:\projects\classicuo\bin\Release" /Y


    7z a ClassicUO-dev-preview-release.zip "c:\projects\classicuo\bin\Release\*"


    dotnet run --project "c:\projects\classicuo\tools\ManifestCreator\ManifestCreator.csproj" "c:\projects\classicuo\bin\Release" "dev-preview" "ClassicUO-dev-preview-release.zip"
artifacts:
- path: ClassicUO-dev-preview-release.zip
  name: ClassicUO
- path: manifest.xml
  name: manifest
deploy:
- provider: GitHub
  tag: ClassicUO-dev-preview
  release: ClassicUO-dev-preview
  description: 'Appveyor autodeploy.\nThis build may not be safe: use it at your own risk.\nIt does not contain Razor.'
  auth_token:
    secure: sFMPr0POE5r5CFP5XbTD0e5pZVRO/12A3LgkqKVDD2uB2Webo6gstCTm63KzcbaW
  artifact: ClassicUO-dev-preview-release.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: dev
- provider: FTP
  host: ftp.classicuo.eu
  protocol: ftp
  username:
    secure: JaSH/LFfqcrUBZ5USwkYozDFFZUmyRZJyxsB/LSNOlI=
  password:
    secure: 4MpoM3vP2gdRcg6YktGA9g==
  folder: /www.classicuo.eu/dev/deploy
  artifact: ClassicUO-dev-preview-release.zip, manifest
  active_mode: false
  beta: false
  debug: false
  on:
    branch: dev
